<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (DB::table('countries')->count() > 0) {
            return;
        }
        DB::table('countries')->insert([
            ['created_at' => Carbon::now(), 'name' => "Afghanistan", 'phone_code' => "93"],
            ['created_at' => Carbon::now(), 'name' => "Aland Islands", 'phone_code' => "340"],
            ['created_at' => Carbon::now(), 'name' => "Albania", 'phone_code' => "355"],
            ['created_at' => Carbon::now(), 'name' => "Algeria", 'phone_code' => "213"],
            ['created_at' => Carbon::now(), 'name' => "American Samoa", 'phone_code' => "-683"],
            ['created_at' => Carbon::now(), 'name' => "Andorra", 'phone_code' => "376"],
            ['created_at' => Carbon::now(), 'name' => "Angola", 'phone_code' => "244"],
            ['created_at' => Carbon::now(), 'name' => "Anguilla", 'phone_code' => "-263"],
            ['created_at' => Carbon::now(), 'name' => "Antarctica", 'phone_code' => "672"],
            ['created_at' => Carbon::now(), 'name' => "Antigua And Barbuda", 'phone_code' => "-267"],
            ['created_at' => Carbon::now(), 'name' => "Argentina", 'phone_code' => "54"],
            ['created_at' => Carbon::now(), 'name' => "Armenia", 'phone_code' => "374"],
            ['created_at' => Carbon::now(), 'name' => "Aruba", 'phone_code' => "297"],
            ['created_at' => Carbon::now(), 'name' => "Australia", 'phone_code' => "61"],
            ['created_at' => Carbon::now(), 'name' => "Austria", 'phone_code' => "43"],
            ['created_at' => Carbon::now(), 'name' => "Azerbaijan", 'phone_code' => "994"],
            ['created_at' => Carbon::now(), 'name' => "The Bahamas", 'phone_code' => "-241"],
            ['created_at' => Carbon::now(), 'name' => "Bahrain", 'phone_code' => "973"],
            ['created_at' => Carbon::now(), 'name' => "Bangladesh", 'phone_code' => "880"],
            ['created_at' => Carbon::now(), 'name' => "Barbados", 'phone_code' => "-245"],
            ['created_at' => Carbon::now(), 'name' => "Belarus", 'phone_code' => "375"],
            ['created_at' => Carbon::now(), 'name' => "Belgium", 'phone_code' => "32"],
            ['created_at' => Carbon::now(), 'name' => "Belize", 'phone_code' => "501"],
            ['created_at' => Carbon::now(), 'name' => "Benin", 'phone_code' => "229"],
            ['created_at' => Carbon::now(), 'name' => "Bermuda", 'phone_code' => "-440"],
            ['created_at' => Carbon::now(), 'name' => "Bhutan", 'phone_code' => "975"],
            ['created_at' => Carbon::now(), 'name' => "Bolivia", 'phone_code' => "591"],
            ['created_at' => Carbon::now(), 'name' => "Bosnia and Herzegovina", 'phone_code' => "387"],
            ['created_at' => Carbon::now(), 'name' => "Botswana", 'phone_code' => "267"],
            ['created_at' => Carbon::now(), 'name' => "Bouvet Island", 'phone_code' => "55"],
            ['created_at' => Carbon::now(), 'name' => "Brazil", 'phone_code' => "55"],
            ['created_at' => Carbon::now(), 'name' => "British Indian Ocean Territory", 'phone_code' => "246"],
            ['created_at' => Carbon::now(), 'name' => "Brunei", 'phone_code' => "673"],
            ['created_at' => Carbon::now(), 'name' => "Bulgaria", 'phone_code' => "359"],
            ['created_at' => Carbon::now(), 'name' => "Burkina Faso", 'phone_code' => "226"],
            ['created_at' => Carbon::now(), 'name' => "Burundi", 'phone_code' => "257"],
            ['created_at' => Carbon::now(), 'name' => "Cambodia", 'phone_code' => "855"],
            ['created_at' => Carbon::now(), 'name' => "Cameroon", 'phone_code' => "237"],
            ['created_at' => Carbon::now(), 'name' => "Canada", 'phone_code' => "1"],
            ['created_at' => Carbon::now(), 'name' => "Cape Verde", 'phone_code' => "238"],
            ['created_at' => Carbon::now(), 'name' => "Cayman Islands", 'phone_code' => "-344"],
            ['created_at' => Carbon::now(), 'name' => "Central African Republic", 'phone_code' => "236"],
            ['created_at' => Carbon::now(), 'name' => "Chad", 'phone_code' => "235"],
            ['created_at' => Carbon::now(), 'name' => "Chile", 'phone_code' => "56"],
            ['created_at' => Carbon::now(), 'name' => "China", 'phone_code' => "86"],
            ['created_at' => Carbon::now(), 'name' => "Christmas Island", 'phone_code' => "61"],
            ['created_at' => Carbon::now(), 'name' => "Cocos (Keeling) Islands", 'phone_code' => "61"],
            ['created_at' => Carbon::now(), 'name' => "Colombia", 'phone_code' => "57"],
            ['created_at' => Carbon::now(), 'name' => "Comoros", 'phone_code' => "269"],
            ['created_at' => Carbon::now(), 'name' => "Congo", 'phone_code' => "242"],
            ['created_at' => Carbon::now(), 'name' => "Democratic Republic of the Congo", 'phone_code' => "243"],
            ['created_at' => Carbon::now(), 'name' => "Cook Islands", 'phone_code' => "682"],
            ['created_at' => Carbon::now(), 'name' => "Costa Rica", 'phone_code' => "506"],
            ['created_at' => Carbon::now(), 'name' => "Cote D'Ivoire (Ivory Coast)", 'phone_code' => "225"],
            ['created_at' => Carbon::now(), 'name' => "Croatia", 'phone_code' => "385"],
            ['created_at' => Carbon::now(), 'name' => "Cuba", 'phone_code' => "53"],
            ['created_at' => Carbon::now(), 'name' => "Cyprus", 'phone_code' => "357"],
            ['created_at' => Carbon::now(), 'name' => "Czech Republic", 'phone_code' => "420"],
            ['created_at' => Carbon::now(), 'name' => "Denmark", 'phone_code' => "45"],
            ['created_at' => Carbon::now(), 'name' => "Djibouti", 'phone_code' => "253"],
            ['created_at' => Carbon::now(), 'name' => "Dominica", 'phone_code' => "-766"],
            ['created_at' => Carbon::now(), 'name' => "Dominican Republic", 'phone_code' => "+1-809 and 1-829"],
            ['created_at' => Carbon::now(), 'name' => "East Timor", 'phone_code' => "670"],
            ['created_at' => Carbon::now(), 'name' => "Ecuador", 'phone_code' => "593"],
            ['created_at' => Carbon::now(), 'name' => "Egypt", 'phone_code' => "20"],
            ['created_at' => Carbon::now(), 'name' => "El Salvador", 'phone_code' => "503"],
            ['created_at' => Carbon::now(), 'name' => "Equatorial Guinea", 'phone_code' => "240"],
            ['created_at' => Carbon::now(), 'name' => "Eritrea", 'phone_code' => "291"],
            ['created_at' => Carbon::now(), 'name' => "Estonia", 'phone_code' => "372"],
            ['created_at' => Carbon::now(), 'name' => "Ethiopia", 'phone_code' => "251"],
            ['created_at' => Carbon::now(), 'name' => "Falkland Islands", 'phone_code' => "500"],
            ['created_at' => Carbon::now(), 'name' => "Faroe Islands", 'phone_code' => "298"],
            ['created_at' => Carbon::now(), 'name' => "Fiji Islands", 'phone_code' => "679"],
            ['created_at' => Carbon::now(), 'name' => "Finland", 'phone_code' => "358"],
            ['created_at' => Carbon::now(), 'name' => "France", 'phone_code' => "33"],
            ['created_at' => Carbon::now(), 'name' => "French Guiana", 'phone_code' => "594"],
            ['created_at' => Carbon::now(), 'name' => "French Polynesia", 'phone_code' => "689"],
            ['created_at' => Carbon::now(), 'name' => "French Southern Territories", 'phone_code' => "262"],
            ['created_at' => Carbon::now(), 'name' => "Gabon", 'phone_code' => "241"],
            ['created_at' => Carbon::now(), 'name' => "Gambia The", 'phone_code' => "220"],
            ['created_at' => Carbon::now(), 'name' => "Georgia", 'phone_code' => "995"],
            ['created_at' => Carbon::now(), 'name' => "Germany", 'phone_code' => "49"],
            ['created_at' => Carbon::now(), 'name' => "Ghana", 'phone_code' => "233"],
            ['created_at' => Carbon::now(), 'name' => "Gibraltar", 'phone_code' => "350"],
            ['created_at' => Carbon::now(), 'name' => "Greece", 'phone_code' => "30"],
            ['created_at' => Carbon::now(), 'name' => "Greenland", 'phone_code' => "299"],
            ['created_at' => Carbon::now(), 'name' => "Grenada", 'phone_code' => "-472"],
            ['created_at' => Carbon::now(), 'name' => "Guadeloupe", 'phone_code' => "590"],
            ['created_at' => Carbon::now(), 'name' => "Guam", 'phone_code' => "-670"],
            ['created_at' => Carbon::now(), 'name' => "Guatemala", 'phone_code' => "502"],
            ['created_at' => Carbon::now(), 'name' => "Guernsey and Alderney", 'phone_code' => "-1437"],
            ['created_at' => Carbon::now(), 'name' => "Guinea", 'phone_code' => "224"],
            ['created_at' => Carbon::now(), 'name' => "Guinea-Bissau", 'phone_code' => "245"],
            ['created_at' => Carbon::now(), 'name' => "Guyana", 'phone_code' => "592"],
            ['created_at' => Carbon::now(), 'name' => "Haiti", 'phone_code' => "509"],
            ['created_at' => Carbon::now(), 'name' => "Heard Island and McDonald Islands", 'phone_code' => "672"],
            ['created_at' => Carbon::now(), 'name' => "Honduras", 'phone_code' => "504"],
            ['created_at' => Carbon::now(), 'name' => "Hong Kong S.A.R.", 'phone_code' => "852"],
            ['created_at' => Carbon::now(), 'name' => "Hungary", 'phone_code' => "36"],
            ['created_at' => Carbon::now(), 'name' => "Iceland", 'phone_code' => "354"],
            ['created_at' => Carbon::now(), 'name' => "India", 'phone_code' => "91"],
            ['created_at' => Carbon::now(), 'name' => "Indonesia", 'phone_code' => "62"],
            ['created_at' => Carbon::now(), 'name' => "Iran", 'phone_code' => "98"],
            ['created_at' => Carbon::now(), 'name' => "Iraq", 'phone_code' => "964"],
            ['created_at' => Carbon::now(), 'name' => "Ireland", 'phone_code' => "353"],
            ['created_at' => Carbon::now(), 'name' => "Israel", 'phone_code' => "972"],
            ['created_at' => Carbon::now(), 'name' => "Italy", 'phone_code' => "39"],
            ['created_at' => Carbon::now(), 'name' => "Jamaica", 'phone_code' => "-875"],
            ['created_at' => Carbon::now(), 'name' => "Japan", 'phone_code' => "81"],
            ['created_at' => Carbon::now(), 'name' => "Jersey", 'phone_code' => "-1490"],
            ['created_at' => Carbon::now(), 'name' => "Jordan", 'phone_code' => "962"],
            ['created_at' => Carbon::now(), 'name' => "Kazakhstan", 'phone_code' => "7"],
            ['created_at' => Carbon::now(), 'name' => "Kenya", 'phone_code' => "254"],
            ['created_at' => Carbon::now(), 'name' => "Kiribati", 'phone_code' => "686"],
            ['created_at' => Carbon::now(), 'name' => "North Korea", 'phone_code' => "850"],
            ['created_at' => Carbon::now(), 'name' => "South Korea", 'phone_code' => "82"],
            ['created_at' => Carbon::now(), 'name' => "Kuwait", 'phone_code' => "965"],
            ['created_at' => Carbon::now(), 'name' => "Kyrgyzstan", 'phone_code' => "996"],
            ['created_at' => Carbon::now(), 'name' => "Laos", 'phone_code' => "856"],
            ['created_at' => Carbon::now(), 'name' => "Latvia", 'phone_code' => "371"],
            ['created_at' => Carbon::now(), 'name' => "Lebanon", 'phone_code' => "961"],
            ['created_at' => Carbon::now(), 'name' => "Lesotho", 'phone_code' => "266"],
            ['created_at' => Carbon::now(), 'name' => "Liberia", 'phone_code' => "231"],
            ['created_at' => Carbon::now(), 'name' => "Libya", 'phone_code' => "218"],
            ['created_at' => Carbon::now(), 'name' => "Liechtenstein", 'phone_code' => "423"],
            ['created_at' => Carbon::now(), 'name' => "Lithuania", 'phone_code' => "370"],
            ['created_at' => Carbon::now(), 'name' => "Luxembourg", 'phone_code' => "352"],
            ['created_at' => Carbon::now(), 'name' => "Macau S.A.R.", 'phone_code' => "853"],
            ['created_at' => Carbon::now(), 'name' => "North Macedonia", 'phone_code' => "389"],
            ['created_at' => Carbon::now(), 'name' => "Madagascar", 'phone_code' => "261"],
            ['created_at' => Carbon::now(), 'name' => "Malawi", 'phone_code' => "265"],
            ['created_at' => Carbon::now(), 'name' => "Malaysia", 'phone_code' => "60"],
            ['created_at' => Carbon::now(), 'name' => "Maldives", 'phone_code' => "960"],
            ['created_at' => Carbon::now(), 'name' => "Mali", 'phone_code' => "223"],
            ['created_at' => Carbon::now(), 'name' => "Malta", 'phone_code' => "356"],
            ['created_at' => Carbon::now(), 'name' => "Man (Isle of)", 'phone_code' => "-1580"],
            ['created_at' => Carbon::now(), 'name' => "Marshall Islands", 'phone_code' => "692"],
            ['created_at' => Carbon::now(), 'name' => "Martinique", 'phone_code' => "596"],
            ['created_at' => Carbon::now(), 'name' => "Mauritania", 'phone_code' => "222"],
            ['created_at' => Carbon::now(), 'name' => "Mauritius", 'phone_code' => "230"],
            ['created_at' => Carbon::now(), 'name' => "Mayotte", 'phone_code' => "262"],
            ['created_at' => Carbon::now(), 'name' => "Mexico", 'phone_code' => "52"],
            ['created_at' => Carbon::now(), 'name' => "Micronesia", 'phone_code' => "691"],
            ['created_at' => Carbon::now(), 'name' => "Moldova", 'phone_code' => "373"],
            ['created_at' => Carbon::now(), 'name' => "Monaco", 'phone_code' => "377"],
            ['created_at' => Carbon::now(), 'name' => "Mongolia", 'phone_code' => "976"],
            ['created_at' => Carbon::now(), 'name' => "Montenegro", 'phone_code' => "382"],
            ['created_at' => Carbon::now(), 'name' => "Montserrat", 'phone_code' => "-663"],
            ['created_at' => Carbon::now(), 'name' => "Morocco", 'phone_code' => "212"],
            ['created_at' => Carbon::now(), 'name' => "Mozambique", 'phone_code' => "258"],
            ['created_at' => Carbon::now(), 'name' => "Myanmar", 'phone_code' => "95"],
            ['created_at' => Carbon::now(), 'name' => "Namibia", 'phone_code' => "264"],
            ['created_at' => Carbon::now(), 'name' => "Nauru", 'phone_code' => "674"],
            ['created_at' => Carbon::now(), 'name' => "Nepal", 'phone_code' => "977"],
            ['created_at' => Carbon::now(), 'name' => "Bonaire, Sint Eustatius and Saba", 'phone_code' => "599"],
            ['created_at' => Carbon::now(), 'name' => "Netherlands", 'phone_code' => "31"],
            ['created_at' => Carbon::now(), 'name' => "New Caledonia", 'phone_code' => "687"],
            ['created_at' => Carbon::now(), 'name' => "New Zealand", 'phone_code' => "64"],
            ['created_at' => Carbon::now(), 'name' => "Nicaragua", 'phone_code' => "505"],
            ['created_at' => Carbon::now(), 'name' => "Niger", 'phone_code' => "227"],
            ['created_at' => Carbon::now(), 'name' => "Nigeria", 'phone_code' => "234"],
            ['created_at' => Carbon::now(), 'name' => "Niue", 'phone_code' => "683"],
            ['created_at' => Carbon::now(), 'name' => "Norfolk Island", 'phone_code' => "672"],
            ['created_at' => Carbon::now(), 'name' => "Northern Mariana Islands", 'phone_code' => "-669"],
            ['created_at' => Carbon::now(), 'name' => "Norway", 'phone_code' => "47"],
            ['created_at' => Carbon::now(), 'name' => "Oman", 'phone_code' => "968"],
            ['created_at' => Carbon::now(), 'name' => "Pakistan", 'phone_code' => "92"],
            ['created_at' => Carbon::now(), 'name' => "Palau", 'phone_code' => "680"],
            ['created_at' => Carbon::now(), 'name' => "Palestinian Territory Occupied", 'phone_code' => "970"],
            ['created_at' => Carbon::now(), 'name' => "Panama", 'phone_code' => "507"],
            ['created_at' => Carbon::now(), 'name' => "Papua new Guinea", 'phone_code' => "675"],
            ['created_at' => Carbon::now(), 'name' => "Paraguay", 'phone_code' => "595"],
            ['created_at' => Carbon::now(), 'name' => "Peru", 'phone_code' => "51"],
            ['created_at' => Carbon::now(), 'name' => "Philippines", 'phone_code' => "63"],
            ['created_at' => Carbon::now(), 'name' => "Pitcairn Island", 'phone_code' => "870"],
            ['created_at' => Carbon::now(), 'name' => "Poland", 'phone_code' => "48"],
            ['created_at' => Carbon::now(), 'name' => "Portugal", 'phone_code' => "351"],
            ['created_at' => Carbon::now(), 'name' => "Puerto Rico", 'phone_code' => "+1-787 and 1-939"],
            ['created_at' => Carbon::now(), 'name' => "Qatar", 'phone_code' => "974"],
            ['created_at' => Carbon::now(), 'name' => "Reunion", 'phone_code' => "262"],
            ['created_at' => Carbon::now(), 'name' => "Romania", 'phone_code' => "40"],
            ['created_at' => Carbon::now(), 'name' => "Russia", 'phone_code' => "7"],
            ['created_at' => Carbon::now(), 'name' => "Rwanda", 'phone_code' => "250"],
            ['created_at' => Carbon::now(), 'name' => "Saint Helena", 'phone_code' => "290"],
            ['created_at' => Carbon::now(), 'name' => "Saint Kitts And Nevis", 'phone_code' => "-868"],
            ['created_at' => Carbon::now(), 'name' => "Saint Lucia", 'phone_code' => "-757"],
            ['created_at' => Carbon::now(), 'name' => "Saint Pierre and Miquelon", 'phone_code' => "508"],
            ['created_at' => Carbon::now(), 'name' => "Saint Vincent And The Grenadines", 'phone_code' => "-783"],
            ['created_at' => Carbon::now(), 'name' => "Saint-Barthelemy", 'phone_code' => "590"],
            ['created_at' => Carbon::now(), 'name' => "Saint-Martin (French part)", 'phone_code' => "590"],
            ['created_at' => Carbon::now(), 'name' => "Samoa", 'phone_code' => "685"],
            ['created_at' => Carbon::now(), 'name' => "San Marino", 'phone_code' => "378"],
            ['created_at' => Carbon::now(), 'name' => "Sao Tome and Principe", 'phone_code' => "239"],
            ['created_at' => Carbon::now(), 'name' => "Saudi Arabia", 'phone_code' => "966"],
            ['created_at' => Carbon::now(), 'name' => "Senegal", 'phone_code' => "221"],
            ['created_at' => Carbon::now(), 'name' => "Serbia", 'phone_code' => "381"],
            ['created_at' => Carbon::now(), 'name' => "Seychelles", 'phone_code' => "248"],
            ['created_at' => Carbon::now(), 'name' => "Sierra Leone", 'phone_code' => "232"],
            ['created_at' => Carbon::now(), 'name' => "Singapore", 'phone_code' => "65"],
            ['created_at' => Carbon::now(), 'name' => "Slovakia", 'phone_code' => "421"],
            ['created_at' => Carbon::now(), 'name' => "Slovenia", 'phone_code' => "386"],
            ['created_at' => Carbon::now(), 'name' => "Solomon Islands", 'phone_code' => "677"],
            ['created_at' => Carbon::now(), 'name' => "Somalia", 'phone_code' => "252"],
            ['created_at' => Carbon::now(), 'name' => "South Africa", 'phone_code' => "27"],
            ['created_at' => Carbon::now(), 'name' => "South Georgia", 'phone_code' => "500"],
            ['created_at' => Carbon::now(), 'name' => "South Sudan", 'phone_code' => "211"],
            ['created_at' => Carbon::now(), 'name' => "Spain", 'phone_code' => "34"],
            ['created_at' => Carbon::now(), 'name' => "Sri Lanka", 'phone_code' => "94"],
            ['created_at' => Carbon::now(), 'name' => "Sudan", 'phone_code' => "249"],
            ['created_at' => Carbon::now(), 'name' => "Suriname", 'phone_code' => "597"],
            ['created_at' => Carbon::now(), 'name' => "Svalbard And Jan Mayen Islands", 'phone_code' => "47"],
            ['created_at' => Carbon::now(), 'name' => "Swaziland", 'phone_code' => "268"],
            ['created_at' => Carbon::now(), 'name' => "Sweden", 'phone_code' => "46"],
            ['created_at' => Carbon::now(), 'name' => "Switzerland", 'phone_code' => "41"],
            ['created_at' => Carbon::now(), 'name' => "Syria", 'phone_code' => "963"],
            ['created_at' => Carbon::now(), 'name' => "Taiwan", 'phone_code' => "886"],
            ['created_at' => Carbon::now(), 'name' => "Tajikistan", 'phone_code' => "992"],
            ['created_at' => Carbon::now(), 'name' => "Tanzania", 'phone_code' => "255"],
            ['created_at' => Carbon::now(), 'name' => "Thailand", 'phone_code' => "66"],
            ['created_at' => Carbon::now(), 'name' => "Togo", 'phone_code' => "228"],
            ['created_at' => Carbon::now(), 'name' => "Tokelau", 'phone_code' => "690"],
            ['created_at' => Carbon::now(), 'name' => "Tonga", 'phone_code' => "676"],
            ['created_at' => Carbon::now(), 'name' => "Trinidad And Tobago", 'phone_code' => "-867"],
            ['created_at' => Carbon::now(), 'name' => "Tunisia", 'phone_code' => "216"],
            ['created_at' => Carbon::now(), 'name' => "Turkey", 'phone_code' => "90"],
            ['created_at' => Carbon::now(), 'name' => "Turkmenistan", 'phone_code' => "993"],
            ['created_at' => Carbon::now(), 'name' => "Turks And Caicos Islands", 'phone_code' => "-648"],
            ['created_at' => Carbon::now(), 'name' => "Tuvalu", 'phone_code' => "688"],
            ['created_at' => Carbon::now(), 'name' => "Uganda", 'phone_code' => "256"],
            ['created_at' => Carbon::now(), 'name' => "Ukraine", 'phone_code' => "380"],
            ['created_at' => Carbon::now(), 'name' => "United Arab Emirates", 'phone_code' => "971"],
            ['created_at' => Carbon::now(), 'name' => "United Kingdom", 'phone_code' => "44"],
            ['created_at' => Carbon::now(), 'name' => "United States", 'phone_code' => "1"],
            ['created_at' => Carbon::now(), 'name' => "United States Minor Outlying Islands", 'phone_code' => "1"],
            ['created_at' => Carbon::now(), 'name' => "Uruguay", 'phone_code' => "598"],
            ['created_at' => Carbon::now(), 'name' => "Uzbekistan", 'phone_code' => "998"],
            ['created_at' => Carbon::now(), 'name' => "Vanuatu", 'phone_code' => "678"],
            ['created_at' => Carbon::now(), 'name' => "Vatican City State (Holy See)", 'phone_code' => "379"],
            ['created_at' => Carbon::now(), 'name' => "Venezuela", 'phone_code' => "58"],
            ['created_at' => Carbon::now(), 'name' => "Vietnam", 'phone_code' => "84"],
            ['created_at' => Carbon::now(), 'name' => "Virgin Islands (British)", 'phone_code' => "-283"],
            ['created_at' => Carbon::now(), 'name' => "Virgin Islands (US)", 'phone_code' => "-339"],
            ['created_at' => Carbon::now(), 'name' => "Wallis And Futuna Islands", 'phone_code' => "681"],
            ['created_at' => Carbon::now(), 'name' => "Western Sahara", 'phone_code' => "212"],
            ['created_at' => Carbon::now(), 'name' => "Yemen", 'phone_code' => "967"],
            ['created_at' => Carbon::now(), 'name' => "Zambia", 'phone_code' => "260"],
            ['created_at' => Carbon::now(), 'name' => "Zimbabwe", 'phone_code' => "263"],
            ['created_at' => Carbon::now(), 'name' => "Kosovo", 'phone_code' => "383"],
            ['created_at' => Carbon::now(), 'name' => "CuraÃ§ao", 'phone_code' => "599"],
            ['created_at' => Carbon::now(), 'name' => "Sint Maarten (Dutch part)", 'phone_code' => "1721"],

        ]);
    }
}
